apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: application
type: Opaque
stringData:
  host: "postgresql.postgresql.svc.cluster.local"
  dbname: "fastapi"
  username: "fadel"
  password: "hjgdke823GJD"
  port: "5432"