apiVersion: v1
kind: Service
metadata:
  name: simplefastapiapp
  namespace: application
spec:
  selector:
    app: simplefastapiapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30006
  type: NodePort